### ISSUE TITLE
ignore pre releases by default

### ISSUE THREAD

**Issue by ToBinio** [PaulDance/cargo-liner#17] opened 2024-02-12 17:33 UTC
**Description**
some packages have pre-releases e.g. [tauri cli](https://crates.io/crates/tauri-cli) 

currently, these versions do not get installed but `liner` things the currently installed version is out of date. So it tries to install them every time just to not install them since the most recent stable release is already installed

**Preferred solution**
ignore all pre-releases by default and add a CLI flag or config entry to install pre-releases

**Additional context**
I believe `cargo search` is not able to return the latest stable release so for this feature it would probably be necessary to replace `cargo search` with something like [`crates index`](https://crates.io/crates/crates-index)

note:
I would be able/interested in trying to implement this

**Comment by PaulDance** [comment] 2024-02-12 21:30
Hi again!

This seems very much like a duplicate of #8 that already describes this issue at length. I'll therefore close the current one as such.

Feel free to re-open it if you feel that was a mistake, however. Also, to add anything you feel missing from the first issue.

The most promising resolution lead I have for it right now is to add a `--dry-run` CLI option directly to `cargo install` itself, like I mentioned in the other issue. Regarding the CLI option to force a pre-release, I'll very probably take a look at it right after fixing the problem.

Cheers,
Paul.

**Closed by PaulDance** 2024-02-12 21:30 UTC
Labels: bug, duplicate, enhancement
